### PR TITLE
initial cpu and mps support

### PR DESCRIPTION
**Pull request by BBC-Esq**
The goal is to us the available pytorch compute devices whenever pytorch is used - e.g. cuda, mps or cpu.  A function within ```utils.py``` can be called to determine the appropriate compute device based on a user's setup.  However, since mps doesn't currently support operations that vocoder and "encoder" require, those are set to either "cuda" or "cpu" (when mps is available as well as only cpu is available).

Note:  "cuda" device obviously refers to nvidia gpus.  However it's also used for AMD gpus running on Linux (provided rocM is installed).  This was done so programmers could use the same API depending on a user's specific GPU.  AMD+Windows is not yet supported by pytorch, this pull request should use "cpu" under that circumstance.

Hence, "cuda," "mps" or "cpu" being the available options that are set by the ```get_compute_device``` function within ```utils.py```.  For vocoder and "encoder," however, only "cuda" or "cpu" are set specifically in since "mps" is not yet available for them....

### CODE REVIEW

**Review by jpc — APPROVED** [review]
That looks great, thanks a lot.

**Comment by BBC-Esq** [comment]
Should incorporate all changes by @akorzh as discussed in the "issue" for this pull request, plus my centralization of a function to determine the appropriate compute device.  His changes were subsequently tested as working on systems with mps but please test that it's still properly assigning the compute devices and the program works as a whole for cuda/mps and/or cpu-only based compute systems...

**Comment by BBC-Esq** [comment]
> That looks great, thanks a lot.

Should be ready for review and testing.

**Comment by jpc** [comment]
That looks great, thanks a lot. I believe all of the commits are really logically a single "change". Would you mind pushing a single squashed commit for merging (unfortunately GitHub does not offer a "squash and rebase" option)?

**Comment by BBC-Esq** [comment]
> That looks great, thanks a lot. I believe all of the commits are really logically a single "change". Would you mind pushing a single squashed commit for merging (unfortunately GitHub does not offer a "squash and rebase" option)?

I don't know what a "squashed commit" is, but I'll ask Chat-gpt.  ;-)

**Comment by BBC-Esq** [comment]
I tried squashing via the command line, using instructions from chat-gpt since I'd never done it before, but it "closed" this pull request for some reason and I can't see how to re-open it.  I've obviously never done this before.  Here's the steps I performed:

1) Cloned the repository, created a command prompt, navigated to the appropriate directory.
2) ran ```git checkout cpu-mps-support (name of my branch).```
3) ran ```git rebase -i --root```
4) my text editor opened and I changed all instances of "pick" to "squash" except the first instance of "pick."
5) saved the file and closed the text editor, and then github proceeded...
6) it opened another txt file with comments regarding the various commits.  I deleted all and made one comprehensive message.  Saved and closed the txt file.
7) ran this command ```git push origin cpu-mps-support --force```

After that I notice that the pull request was closed on your repository...Please help, this is my first time doing this.

**Comment by jpc** [comment]
Hey, your steps looks perfect to me and the line "[BBC-Esq](https://github.com/BBC-Esq) [force-pushed](https://github.com/collabora/WhisperSpeech/compare/280d756965b3efa9b86f5a0963ecf932b95900a9..ab3af853d1d3c11d4f7953d9a68f275d4b5de40c) the cpu-mps-support  branch from [280d756 ](https://github.com/collabora/WhisperSpeech/commit/280d756965b3efa9b86f5a0963ecf932b95900a9)to [ab3af85 ](https://github.com/collabora/WhisperSpeech/commit/ab3af853d1d3c11d4f7953d9a68f275d4b5de40c)[yesterday](https://github.com/collabora/WhisperSpeech/pull/77#event-11788363734)" here suggests you did it perfectly (there are no diffs to the previous version but it's now a new single commit)... Congrats on your first interactive rebase! :)

It seems like the pull request was closed because something deleted the branch you force-pushed. But this happened 1,5hours later so it was not your squashing (you can check the precise timestamps by hovering over the fuzzy "yesterday" and "20 hour ago" labels on GitHub).

**Comment by jpc** [comment]
And sorry for having you do all this work, it's sometimes hard to know what's going to be an easy fix and what requires someone to spend a lot of time. I was working with git for 10+ years so I unfortunately mostly forgot what is easy and what is hard...

I sincerely hope it will pay off in the longer run but if you feel something I asked for takes a lot of time then also feel free to push back a bit.  :)

**Pull request closed without merging**
