### PR TITLE
CPU + MPS Support Updated

### PR DESCRIPTION
**Pull request by signalprime**
Original MPS compatability updates are credited to @akorzh as discussed in [CPU + MPS Support](https://github.com/collabora/WhisperSpeech/issues/56).  Additional implementation for multi-device compatability is credited to @BBC-Esq and his work from [PR #89](https://github.com/collabora/WhisperSpeech/pull/89).  

I filled in some missing details, updated components to meet the changes by @akorzh, and worked to ensure a more seamless cross-platform compatability.  Other small updates include relative imports for whisperspeech components as part of best practices.  

Finally, I suggest that the `requirements.txt` file be reintroduced and `webdataset` added to the standard portion and not just the dev install until further updates in order to avoid issues with end-users who would not normally install the development set of requirements.

### CODE REVIEW

**Comment by signalprime** [comment]
Also, all credit to the original authors and @collaborasysadmin: in my opinion this is SOTA and the best open-source TTS library available.

**Comment by BBC-Esq** [comment]
Wish I could test it's MPS aspect but I'm Windows-trained!

**Comment by BBC-Esq** [comment]
This may be a little verbose for this conversation, but can you help me understand what can be on CUDA/MPS/CPU.  For example, "these things must be on CUDA or CPU" but the rest can be on CUDA/MPS/CPU.  I'm not a programmer by trade, but I am willing to put in some time to learn about these things and would like to continue to contribute.

e.g. - this tensor from vocodor cannot be on mps...this model can't be on mps, etc?  Maybe post in the "Issue" instead of here?

**Comment by signalprime** [comment]
Yes, I'll write back on [CPU + MPS Support](https://github.com/collabora/WhisperSpeech/issues/56).  Long story short, it's just a matter of some core components, which are widely used downstream, getting MPS support.  Here is a list of open items https://github.com/pytorch/pytorch/issues/77764# and a features support document published by apple https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf. The holes are being closed, but a few have been open for so long, like AMP and pytorch autocast which I often run into.  I think on this project, if I remember correctly when working to enable MPS, I ran into a flash attention issue.  I dug in on it but ran out of time and then noticed @akorzh had already made the workarounds that we're using now.

**Comment by cocktailpeanut** [comment]
I've tested but getting the same error.

Just to be clear, this happens not at start, but right AFTER the inference has finished, as can be seen below (100% progress)

```
source /Users/x/pinokio/api/whisperspeech/env/bin/activate /Users/x/pinokio/api/whisperspeech/env && python app.py
/Users/x/pinokio/api/whisperspeech/env/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
['  This is the first demo of Whisper Speech, a fully open source text-to-speech model trained by Collabora and Lion on the Juwels supercomputer.  '] ['en']
Traceback (most recent call last):████████████████████████████████████████████████████████████████████| 100.00% [752/752 01:10<00:00]
  File "/Users/x/pinokio/api/whisperspeech/env/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/Users/x/pinokio/api/whisperspeech/env/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/Users/x/pinokio/api/whisperspeech/env/lib/python3.10/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "/Users/x/pinokio/api/whisperspeech/env/lib/python3.10/site-packages/gradio/blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/x/pinokio/api/whisperspeech/env/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/Users/x/pinokio/api/whisperspeech/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/Users/x/pinokio/api/whisperspeech/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/Users/x/pinokio/api/whisperspeech/env/lib/python3.10/site-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "/Users/x/pinokio/api/whisperspeech/app.py", line 47, in whisper_speech_demo
    audio = generate_audio(pipe, segments, speaker_audio, speaker_url, cps)
  File "/Users/x/pinokio/api/whisperspeech/app.py", line 38, in generate_audio
    audio = pipe.vocoder.decode(atoks)
  File "/Users/x/pinokio/api/whisperspeech/env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/x/pinokio/api/whisperspeech/env/lib/python3.10/site-packages/whisperspeech/a2wav.py", line 38, in decode
    features = self.vocos.codes_to_features(atoks)
  File "/Users/x/pinokio/api/whisperspeech/env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/x/pinokio/api/whisperspeech/env/lib/python3.10/site-packages/vocos/pretrained.py", line 140, in codes_to_features
    features = torch.nn.functional.embedding(embeddings_idxs, self.feature_extractor.codebook_weights).sum(dim=0)
  File "/Users/x/pinokio/api/whisperspeech/env/lib/python3.10/site-packages/torch/nn/functional.py", line 2264, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Placeholder storage has not been allocated on MPS device!
```


> I also ensured that utils was being imported from the relative path since that initially caused an error if the user was using it as an installed package rather than executing from inside the whisperspeech directory.

@signalprime have you tested this not as part of the project but as a library installed from a separate project? If it's working in your environment, the only speculation I can think of is because of some difference between when you clone this repo and run the notebook vs. importing this as a library from an external app.

I tested by creating an app that imports whisperspeech, and installing through the following requirements.txt file:

```
git+https://github.com/collabora/WhisperSpeech@refs/pull/93/head
webdataset          # since this doesn't seem to be included in this PR (shouldn't this be included? Otherwise it won't be usable as a pip package
```

Happy to provide any more info. Thanks!

**Comment by signalprime** [comment]
I'm reviewing at this time and will update this message shortly

**Comment by BBC-Esq** [comment]
If/when this app gets up and running, might be a good thing to upload to the "examples" folder...

**Comment by signalprime** [comment]
@cocktailpeanut if you've installed this PR using pip, then your example will work after the following update to `generate_audio`.  I've tested with `torch >= 2.1.0`.
```
def generate_audio(pipe, segments, speaker, speaker_url, cps=14):
    if isinstance(speaker, (str, Path)): speaker = pipe.extract_spk_emb(speaker)
    elif speaker_url: speaker = pipe.extract_spk_emb(speaker_url)
    else: speaker = pipe.default_speaker
    langs, texts = [list(x) for x in zip(*segments)]
    print(texts, langs)
    stoks = pipe.t2s.generate(texts, cps=cps, lang=langs)[0]
    atoks = pipe.s2a.generate(stoks, speaker.unsqueeze(0))
    audio = pipe.vocoder.decode(atoks.to("cpu")) # <-- `atoks` needs to be on the CPU because the torch ops within vocoder aren't yet MPS compatible
    return audio
```

The inference notebook and gradio app work for me, but I did come across a challenge when building a minimal example:
```
import os
os.environ["PYTORCH_ENABLE_MPS_FALLBACK"] = "1"
from whisperspeech.pipeline import Pipeline

tts_pipe = Pipeline(s2a_ref='collabora/whisperspeech:s2a-q4-tiny-en+pl.model')

save_path = '/tmp/output.wav'
tts_pipe.generate_to_file(save_path, "This is a test") 
```

Producing this error:
```
    self.vocoder.decode_to_file(fname, self.generate_atoks(text, speaker, lang=lang, cps=cps, step_callback=None))
  File "/Users/signalprime/miniconda/envs/WhisperTest/lib/python3.10/site-packages/whisperspeech/a2wav.py", line 48, in decode_to_file
    torchaudio.save(fname, audio.cpu(), 24000)
  File "/Users/signalprime/miniconda/envs/WhisperTest/lib/python3.10/site-packages/torchaudio/_backend/utils.py", line 312, in save
    backend = dispatcher(uri, format, backend)
  File "/Users/signalprime/miniconda/envs/WhisperTest/lib/python3.10/site-packages/torchaudio/_backend/utils.py", line 222, in dispatcher
    raise RuntimeError(f"Couldn't find appropriate backend to handle uri {uri} and format {format}.")

RuntimeError: Couldn't find appropriate backend to handle uri /tmp/output.wav and format None.
```

**Comment by BBC-Esq** [comment]
Sorry to interrupt...I was writing this while you posted your updated edit.  I recall when I tried saving an audio file via torchaudio I had to separately ``` pip install``` torchaudio's backend for some reason.  On Windows I believe I ran ```pip install soundfile``` if I recall.  Even though I installed the proper version of ```torchaudio``` it didn't work until I specifically installed ```soundfile```.  Apparently the backend is different between windows/linux/macos though...

https://pytorch.org/audio/2.0.0/backend.html

See also:

https://pypi.org/project/soundfile/

**Comment by signalprime** [comment]
Great insight, thanks @BBC-Esq, that'll certainly be useful for any FAQ

**Comment by BBC-Esq** [comment]
Thanks, if people like myself who aren't as experienced with jupyter notebooks and such, dev installations, etc., it might be good to start accumulating requirements.txt requirements, which is what I'm more used to.  Liked your suggestion about that on the new pull request.  Would be happy to help to the extent I can of course.  I also had to uninstall the pytorch version that was installed by SpeechBrain and install the CUDA version when testing my script in the examples folder...stuff like that.

**Comment by signalprime** [comment]
You're right, `soundfile` fixed my other environment and the minimal example worked fine.  I updated the settings.ini file with that requirement and also moved the webdataset over to the standard installation.  I'll add a tests folder to put the minimal example, even though it's not a standard unit-test.

**Comment by BBC-Esq** [comment]
Wow, glad it worked.  Just got notices of the updated pull request too.  I don't quite understand why since Pytorch's documentation says that all Linux/MacOS is supposed to come with sox_io...see my revised comment above with an image.

Might be an issue to lookout for.  I researched and we can specify the backend within torchaudio so we may need to do that if this becomes an ongoing issue...

**Comment by signalprime** [comment]
@jpc are you okay with the updates or require any changes?

**Comment by BBC-Esq** [comment]
Good morning all.  I tested the proposed pull request:

Windows
pytorch 2.1.2
and CUDA 11.8

I used the ```text_to_audio_file.py``` script in the "examples" folder.  I ```pip installed``` WhisperSpeech in a virtual environment and other necessary dependencies.  I then copied and pasted all of the modified files on @signalprime fork to the appropriate site-packages, as shown here:

image

I then ran ```text_to_audio_file.py``` and it worked just like it did before.  Therefore,I don't see any regression from a Windows user's perspective.  This obviously didn't test the "cpu" nor "mps" aspects, but thought it was good to know that the pull request doesn't regress cuda usage when cuda is available...at least for the limited functionality of ```text_to_audio_file.py```.

**Comment by cocktailpeanut** [comment]
> @cocktailpeanut if you've installed this PR using pip, then your example will work after the following update to `generate_audio`. I've tested with `torch >= 2.1.0`.
> 
> ```
> def generate_audio(pipe, segments, speaker, speaker_url, cps=14):
>     if isinstance(speaker, (str, Path)): speaker = pipe.extract_spk_emb(speaker)
>     elif speaker_url: speaker = pipe.extract_spk_emb(speaker_url)
>     else: speaker = pipe.default_speaker
>     langs, texts = [list(x) for x in zip(*segments)]
>     print(texts, langs)
>     stoks = pipe.t2s.generate(texts, cps=cps, lang=langs)[0]
>     atoks = pipe.s2a.generate(stoks, speaker.unsqueeze(0))
>     audio = pipe.vocoder.decode(atoks.to("cpu")) # <-- `atoks` needs to be on the CPU because the torch ops within vocoder aren't yet MPS compatible
>     return audio
> ```

Thank you @signalprime I can confirm, with this I was able to get it to work on MPS! cc: @BBC-Esq it works on torch 2.2.0 as well.

**Comment by BBC-Esq** [comment]
@signalprime I added some colored print statements as you can see in the image below.  It's helpful for me, but would it be helpful to you or others such that I should do a pull request in your opinion or just keep it on my branch?  This is running the example script using your most recent pull request modification.  I figured it might be helpful to nail down device/tensor allocations...

image

**Comment by BBC-Esq** [comment]
And we could simply add a flag of True or False at the beginning of the script determine whether to print the debut print statements or not...

**Comment by BBC-Esq** [comment]
I used the ```termcolor``` library as follows as well as ```inspect``` (part of standard python library):

```
import inspect
from termcolor import cprint

def my_cprint(message, color):
    frame = inspect.currentframe().f_back
    script_name = Path(frame.f_code.co_filename).stem
    line_number = frame.f_lineno
    enhanced_message = f"{script_name}:{line_number}: {message}"
    cprint(enhanced_message, color)
```

**Comment by jpc** [comment]
Hey, I love it. Thanks a lot for all the effort you all put into this! :)

Tomorrow I'll review this, test on a fresh MacOS env and merge the changes back into the notebooks so we have everything in sync.

The `webdataset` dependency appeared because we put the helper method in `utils` with all the other dataset-related stuff. It's unfortunate naming of the Python module on my part – the notebook was called "Dataset utilities" and was meant to be used during training only. I'll figure out a better place to put it and then we can avoid adding the dependency for inference.

**Comment by jpc** [comment]
I tested and it worked on both Linux and Mac. I also split up utils to avoid the `webdataset` usage for inference.

Would you mind retesting this on Windows @BBC-Esq once we merge this?

**Comment by BBC-Esq** [comment]
@jpc I successfully tested the new code base on the ```gui_file_to_text_to_audio_playback.py``` script in the examples folder.

Windows 10
CUDA 11.8
Pytorch 2.1.2

Pip installed WhisperSpeech.  Then I manually replaces the scripts within the "site-packges" folder with the ones from the github repository...re-ran, and worked just like before.

**Pull request merged**
