### PR TITLE
Tiny doc fix from apparent copy/paste

### PR DESCRIPTION
**Pull request by vbawa**
The instructions in `text_to_audio_playback.py` still reference `gui_text_to_audio_playback.py`, which might be mildly confusing to some

### CODE REVIEW

**Comment by BBC-Esq** [comment]
In my pull request I actually deleted the first script because I felt it was redundant, but no movement on that pull request yet...but Thanks for pointing that out.  Waiting to see if the pull request is accepted.

**Comment by BBC-Esq** [comment]
I think this was fixed already?

**Comment by vbawa** [comment]
Hm, doesn't seem so: https://github.com/collabora/WhisperSpeech/blob/635ca86ba190e54777d34893ae3966a8eca19b2d/examples/text_to_audio_playback.py#L15

**Comment by BBC-Esq** [comment]
ok

**Comment by jpc** [comment]
Thanks :)

**Pull request merged**
